# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 501)
        self.line1 = QtWidgets.QLineEdit(Form)
        self.line1.setGeometry(QtCore.QRect(120, 300, 141, 21))
        self.line1.setObjectName("line1")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 40, 201, 61))
        self.label.setStyleSheet("font: 28pt \"Sitka Heading\";")
        self.label.setObjectName("label")
        self.push4 = QtWidgets.QPushButton(Form)
        self.push4.setGeometry(QtCore.QRect(120, 260, 141, 23))
        self.push4.setObjectName("push4")
        self.push1 = QtWidgets.QPushButton(Form)
        self.push1.setGeometry(QtCore.QRect(120, 140, 141, 23))
        self.push1.setObjectName("push1")
        self.push2 = QtWidgets.QPushButton(Form)
        self.push2.setGeometry(QtCore.QRect(120, 180, 141, 23))
        self.push2.setObjectName("push2")
        self.push3 = QtWidgets.QPushButton(Form)
        self.push3.setGeometry(QtCore.QRect(120, 220, 141, 23))
        self.push3.setObjectName("push3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "InputDialog"))
        self.push4.setText(_translate("Form", "Выбор пункта из списка"))
        self.push1.setText(_translate("Form", "Ввод строки"))
        self.push2.setText(_translate("Form", "Ввод целого числа"))
        self.push3.setText(_translate("Form", "Ввод вещ. числа"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
