# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unt2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 477)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(80, 10, 241, 40))
        self.label.setObjectName("label")
        self.line = QtWidgets.QLineEdit(Form)
        self.line.setGeometry(QtCore.QRect(140, 80, 113, 20))
        self.line.setObjectName("line")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 340, 160, 94))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button1.setObjectName("button1")
        self.verticalLayout.addWidget(self.button1)
        self.button2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button2.setObjectName("button2")
        self.verticalLayout.addWidget(self.button2)
        self.label2 = QtWidgets.QLabel(Form)
        self.label2.setGeometry(QtCore.QRect(40, 120, 81, 16))
        self.label2.setObjectName("label2")
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setGeometry(QtCore.QRect(40, 80, 81, 16))
        self.label1.setObjectName("label1")
        self.line2 = QtWidgets.QLineEdit(Form)
        self.line2.setGeometry(QtCore.QRect(140, 120, 113, 20))
        self.line2.setObjectName("line2")
        self.line3 = QtWidgets.QLineEdit(Form)
        self.line3.setGeometry(QtCore.QRect(120, 300, 161, 20))
        self.line3.setObjectName("line3")
        self.check = QtWidgets.QCheckBox(Form)
        self.check.setGeometry(QtCore.QRect(50, 180, 141, 20))
        self.check.setObjectName("check")
        self.check2 = QtWidgets.QCheckBox(Form)
        self.check2.setGeometry(QtCore.QRect(50, 210, 171, 20))
        self.check2.setObjectName("check2")
        self.check3 = QtWidgets.QCheckBox(Form)
        self.check3.setGeometry(QtCore.QRect(50, 240, 151, 20))
        self.check3.setObjectName("check3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Нахождение площади параллелограмма"))
        self.button1.setText(_translate("Form", "посчитать"))
        self.button2.setText(_translate("Form", "очистить"))
        self.label2.setText(_translate("Form", "высота"))
        self.label1.setText(_translate("Form", "сторона a"))
        self.check.setText(_translate("Form", "Удвоить площадь"))
        self.check2.setText(_translate("Form", "Делить площадь на два"))
        self.check3.setText(_translate("Form", "Площадь в квадрате"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
