# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 477)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 0, 201, 40))
        self.label.setObjectName("label")
        self.line = QtWidgets.QLineEdit(Form)
        self.line.setGeometry(QtCore.QRect(140, 80, 113, 20))
        self.line.setObjectName("line")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 280, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_1.setObjectName("button_1")
        self.verticalLayout.addWidget(self.button_1)
        self.button_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_2.setObjectName("button_2")
        self.verticalLayout.addWidget(self.button_2)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_1 = QtWidgets.QLabel(Form)
        self.label_1.setGeometry(QtCore.QRect(40, 80, 81, 16))
        self.label_1.setObjectName("label_1")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 200, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 160, 81, 16))
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QLineEdit(Form)
        self.line_2.setGeometry(QtCore.QRect(140, 120, 113, 20))
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QLineEdit(Form)
        self.line_3.setGeometry(QtCore.QRect(140, 160, 113, 20))
        self.line_3.setObjectName("line_3")
        self.lin_4 = QtWidgets.QLineEdit(Form)
        self.lin_4.setGeometry(QtCore.QRect(140, 200, 113, 20))
        self.lin_4.setObjectName("lin_4")
        self.line_5 = QtWidgets.QLineEdit(Form)
        self.line_5.setGeometry(QtCore.QRect(140, 240, 113, 20))
        self.line_5.setObjectName("line_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Периметр разносторонней трапеции"))
        self.button_1.setText(_translate("Form", "посчитать"))
        self.button_2.setText(_translate("Form", "отменить"))
        self.label_2.setText(_translate("Form", "сторона b"))
        self.label_1.setText(_translate("Form", "сторона a"))
        self.label_4.setText(_translate("Form", "сторона d"))
        self.label_3.setText(_translate("Form", "сторона c"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
