# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unt1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(519, 395)
        self.push = QtWidgets.QPushButton(Form)
        self.push.setGeometry(QtCore.QRect(180, 220, 101, 23))
        self.push.setObjectName("push")
        self.push2 = QtWidgets.QPushButton(Form)
        self.push2.setGeometry(QtCore.QRect(180, 260, 101, 23))
        self.push2.setObjectName("push2")
        self.line = QtWidgets.QLineEdit(Form)
        self.line.setGeometry(QtCore.QRect(180, 80, 141, 20))
        self.line.setObjectName("line")
        self.line2 = QtWidgets.QLineEdit(Form)
        self.line2.setGeometry(QtCore.QRect(180, 140, 141, 20))
        self.line2.setObjectName("line2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 60, 121, 16))
        self.label.setObjectName("label")
        self.label2 = QtWidgets.QLabel(Form)
        self.label2.setGeometry(QtCore.QRect(180, 120, 121, 16))
        self.label2.setObjectName("label2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.push.setText(_translate("Form", "Авторизация"))
        self.push2.setText(_translate("Form", "Очистить"))
        self.label.setText(_translate("Form", "Логин"))
        self.label2.setText(_translate("Form", "Пароль"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
