# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unt.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(707, 546)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(40, 20, 641, 481))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(80, 100, 161, 16))
        self.label.setObjectName("label")
        self.line = QtWidgets.QLineEdit(self.tab)
        self.line.setGeometry(QtCore.QRect(80, 140, 361, 20))
        self.line.setObjectName("line")
        self.label2 = QtWidgets.QLabel(self.tab)
        self.label2.setGeometry(QtCore.QRect(80, 200, 161, 16))
        self.label2.setObjectName("label2")
        self.line2 = QtWidgets.QLineEdit(self.tab)
        self.line2.setGeometry(QtCore.QRect(80, 240, 361, 20))
        self.line2.setObjectName("line2")
        self.push2 = QtWidgets.QPushButton(self.tab)
        self.push2.setGeometry(QtCore.QRect(240, 320, 75, 23))
        self.push2.setObjectName("push2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(100, 280, 201, 21))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label3_2 = QtWidgets.QLabel(self.tab_2)
        self.label3_2.setGeometry(QtCore.QRect(40, 60, 381, 261))
        self.label3_2.setText("")
        self.label3_2.setObjectName("label3_2")
        self.push = QtWidgets.QPushButton(self.tab_2)
        self.push.setGeometry(QtCore.QRect(180, 360, 101, 41))
        self.push.setObjectName("push")
        self.label4 = QtWidgets.QLabel(self.tab_2)
        self.label4.setGeometry(QtCore.QRect(460, 200, 81, 16))
        self.label4.setObjectName("label4")
        self.line3 = QtWidgets.QLineEdit(self.tab_2)
        self.line3.setGeometry(QtCore.QRect(460, 220, 113, 20))
        self.line3.setObjectName("line3")
        self.label5 = QtWidgets.QLabel(self.tab_2)
        self.label5.setGeometry(QtCore.QRect(460, 240, 101, 16))
        self.label5.setObjectName("label5")
        self.line4 = QtWidgets.QLineEdit(self.tab_2)
        self.line4.setGeometry(QtCore.QRect(460, 260, 113, 20))
        self.line4.setObjectName("line4")
        self.label6 = QtWidgets.QLabel(self.tab_2)
        self.label6.setGeometry(QtCore.QRect(460, 280, 101, 16))
        self.label6.setObjectName("label6")
        self.line5 = QtWidgets.QLineEdit(self.tab_2)
        self.line5.setGeometry(QtCore.QRect(460, 300, 113, 20))
        self.line5.setObjectName("line5")
        self.label7 = QtWidgets.QLabel(self.tab_2)
        self.label7.setGeometry(QtCore.QRect(460, 320, 101, 16))
        self.label7.setObjectName("label7")
        self.line6 = QtWidgets.QLineEdit(self.tab_2)
        self.line6.setGeometry(QtCore.QRect(460, 340, 113, 20))
        self.line6.setObjectName("line6")
        self.label8 = QtWidgets.QLabel(self.tab_2)
        self.label8.setGeometry(QtCore.QRect(440, 40, 161, 141))
        self.label8.setText("")
        self.label8.setPixmap(QtGui.QPixmap(":/photo/photo.png"))
        self.label8.setScaledContents(True)
        self.label8.setObjectName("label8")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setGeometry(QtCore.QRect(-400, 540, 256, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Первоначальная стоимость"))
        self.line.setText(_translate("Form", "Введите стоимость"))
        self.label2.setText(_translate("Form", "Норма амортизации"))
        self.line2.setText(_translate("Form", "Введите норму"))
        self.push2.setText(_translate("Form", "Посчитать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.push.setText(_translate("Form", "Добавить"))
        self.label4.setText(_translate("Form", "Номер карты"))
        self.label5.setText(_translate("Form", "Имя владельца"))
        self.label6.setText(_translate("Form", "Действительна до"))
        self.label7.setText(_translate("Form", "Задние цифры"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))
import my_photo


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
